README.md
Carthage cannot parse `'` for strings. It also requires the username/organization that the repo can be found in.
=> Update carthage stanza in README

Nuke/Source/Core/ImageMemoryCache.swift
=> Fixed Crash on 32bits Architecture

Documentation/Guides/Installation Guide.md
Hi,
Trying to update for the current beta, I've noticed that you were targeting the `Nuke/Nuke` and that brought an error on `carthage update`
`A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/Nuke/Nuke.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled`
Using `github "kean/Nuke" ~> 4.0` worked great for me.
Thanks for building Nuke,
Francisco
=> fix Carthage wrong target

Sources/Cache.swift
`Cache.add(_:)` does not check to see if a node already exists for a given key. While the existing node in `map` will be overwritten, it will not be removed from `list`.
This PR checks for an `existingNode` in `map` (where `existingNode.value.key == node.value.key`)  and properly removes it.
=> Now removing existing node from linked list when adding node with same key

Sources/DataLoader.swift
From Apple docs:
“In macOS, path is the location at which to store the on-disk cache.
In iOS, path is the name of a subdirectory of the application’s default cache directory in which to store the on-disk cache (the subdirectory is created if it does not exist).”
So this updates the path for macOS accordingly.
=> Fix disk cache path for macOS

Sources/ImageView.swift
Of course, state restoration in landscape mode is mere correlation, but the related selecting of the current table view row exposed itself causing #174.
```swift
selectRow(at:animated:scrollPosition:) - UITableView
```
Investigating further showed, the issue only occurred with quick synchronous memory cache lookup, when `imageCache.cachedResponse(for: request)` returned a response. 
A comment, in `ImageView.swift`, made me curious.
```swift      
// Make sure that view reuse is handled correctly.
self.taskId += 1
let taskId = self.taskId
```
And sure enough, resetting the task identifier after an image cache hit, resolves this issue. 🙌
Unfortunately, I couldn’t come up with a tight test case, reproducing this timing issue. Maybe you can think of way to test this.
Sidebar, why not use …
=> Reset task ID

Sources/Deprecated.swift, Sources/ImageProcessing.swift, Sources/ImageRequest.swift
Hello, so I ran into a problem. I have a required design, and minimal control over my content pipeline. So I rely heavily on client side optimizations. I am only recently trying Nuke, and love it so far, but ran into a little snag, line 157 of ImageProcessing.swift. This `CGFloat(min(scale, 1))` in particular.
What this means is you wouldn't expect anyone to need to upscale an image. Though I use client-side image processing for 2 main reasons (among others).
1. to decode off the main thread, which Nuke does beautifully
2. to ensure there is no scaling using offscreen rendering
The problem is, the images I get back are just slightly smaller than the views they are displayed in, so with this, and the the maximum of scale 1, means the only option is to use UIImageView scaling again. …
=> Allow images to upscale

Sources/ImageRequest.swift, Tests/ImageProcessingTests.swift
- This allows shared custom processors to be provided rather than depending only on factory methods of image requests
e.g.
```swift
let imageRequest = ImageRequest(url: url, processor: MyProccessor.shared)
```
I also added tests for this and my previous pull request for upscaling.
=> allow custom processor through init

Sources/ImageView.swift
Added always transition flag to ImageLoadingOptions, so that you can control whether to show transition even when image is retrieved from cache
=> alwaysTransition flag

Package.swift
Hi Alexander, it looks like your `master` branch is ready for tools v5. Proposed changes make a package working on Mac. Thanks!
=> Swift PM: Add tools version to enable Xcode build

Package.swift
Hey Alexander, it’s me again. Other changes in 7.6 require macOS 10.12, but Xcode uses 10.10 by default. This is a small fix which helps to get rid of all compiler errors related to modern APIs. Thanks!
=> Swift PM: Include platform for code compatibility

.travis.yml, Nuke.xcodeproj/project.pbxproj, README.md, Sources/Internal.swift
Swift 5.0 and Swift 4.2 are source compatible so I expect most project to be updated to Swift 5.0 by the time Nuke 8 is released. In the meantime, I'm going to save a lot of time by not maintaining both versions and it would make it easier to adopt Swift 5 features.
=> Remove Swift 4.2 Support

Demo/Sources/RateLimiterDemoViewController.swift, README.md, Sources/ImagePipeline.swift, Sources/ImageProcessing.swift, Sources/ImageRequest.swift, Tests/ImagePipelineTests.swift, Tests/ImageProcessingTests.swift, Tests/MockImageDecoder.swift, Tests/MockImageProcessor.swift, Tests/ThreadSafetyTests.swift
In the existing solution, `ImageDecompressor` is the default image processor of each `ImageRequest` which was done mostly to reduce the implementation efforts. But to make [#227: Caching Processed Images](https://github.com/kean/Nuke/pull/227) possible, decompression needs to change. At least one of the new scenarios to support is the following: we read the processed image data from disk, no processors need to be applied, but the decompression needs to run.
In the current solution, each request has a default processor - `ImageDecompressor`. The responsibility to decide when to decompress lies on the user and it's easy to make mistakes. Let's look at the following example:
```swift
let request = ImageRequest(url: url)
.processed(by: ImageDecompressor(targetSize: CGSize(width: 40, height: …
```
=> Decoupling Image Decompression

Nuke.xcodeproj/project.pbxproj, Sources/ImagePipeline.swift, Sources/ImageTask.swift, Sources/ImageView.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineProgressiveDecodingTests.swift, Tests/ImagePipelineResumableDataTests.swift, Tests/ImagePipelineTests.swift, Tests/ImageViewTests.swift, Tests/MockImagePipeline.swift
The progressive images were added in the existing `ImageTask` progress handler as a quick solution in Nuke 7. Now it's time to address this.
- Extend `ImagePipeline` API with a new method:
```swift
public func imageTask(with request: ImageRequest, delegate: ImageTaskDelegate) -> ImageTask
```
Unlike the existing `loadImage(with:)` method, the new method isn't marked with `@discardableResult`. This is because the task created by the method isn't started yet. So after you set everything up, you should call `task.start()`.
- Add `ImageTaskDelegate`:
```swift
public protocol ImageTaskDelegate: class {
/// Called when the task finishes loading the image.
func imageTask(_ task: ImageTask, didCompleteWithResponse response: ImageResponse?, error: ImagePipeline.Error?)
/// Called periodically …
```
=> Add ImageTaskDelegate

Sources/ImagePipeline.swift, Sources/ImagePreheater.swift, Sources/ImageRequest.swift, Sources/ImageTask.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineTests.swift, Tests/XCTestCase+Nuke.swift
[Nuke 7.4](https://github.com/kean/Nuke/releases/tag/7.4) contained a new prefetching option: `ImagePreheater.Destination`. In order to implement `.diskCache` destination a new private `.isDecodingDisabled` option was added to `ImageRequest`. With this option enabled, the pipeline after loading data will stop at decoding step and return `.decodingFailed` error instead.
The primary issue with `.isDecodingDisabled` – apart from being a bit confusing – was the fact that is was private and users couldn't use it in their own prefetching implementations. To address this we introduce new `loadData` method to `ImagePipeline` which became possible after merging [#235 ImagePipeline v2](https://github.com/kean/Nuke/pull/235).
=> Add new loadData method to ImagePipeline

Demo/Sources/Helpers/Utilities.swift, Documentation/Guides/Core Image Integration Guide.md, README.md, Sources/ImagePipeline.swift, Sources/ImageProcessing.swift, Sources/ImageRequest.swift, Tests/ImagePipelineTests.swift, Tests/ImageProcessingTests.swift, Tests/ImageRequestTests.swift, Tests/MockImageProcessor.swift, Tests/PerformanceTests.swift, Tests/ThreadSafetyTests.swift
One of the prerequisites for [#227: Caching Processed Images](https://github.com/kean/Nuke/pull/227) is that we should be able to generate cache keys based on the applied image processors. This isn't possible in the current `ImageProcessing` infrastructure.
In order to make #227 possible we change the way we identify image processors. Instead of conforming to `Equatable` each image processor will now return a `String` identifier.
Unfortunately, `String` identifiers are slow. Even doing simple `identifier = "ImageDecompressor\(targetSize)\(contentMode)\(upscale)"` makes the primary `Nuke.loadImage(with:into:)` function _twice_ as slow which is unacceptable. In order to compensate that, each image processors will also be able to (optionally) return a `hashableIdentifier: AnyHashable` which …
=> ImageProcessing String identifiers

README.md, Sources/ImagePipeline.swift, Sources/ImagePreheater.swift, Sources/ImageTask.swift, Sources/ImageView.swift, Tests/Helpers.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineProgressiveDecodingTests.swift, Tests/ImagePipelineTests.swift, Tests/ImageProcessingTests.swift, Tests/ImageTaskMetricsTests.swift, Tests/ImageViewIntegrationTests.swift, Tests/ImageViewTests.swift, Tests/MockImagePipeline.swift, Tests/PerformanceTests.swift, Tests/ThreadSafetyTests.swift, Tests/XCTestCase+Nuke.swift
Adopt `Result` type introduced in Swift 5
=> Adopt Result type

Nuke.xcodeproj/project.pbxproj, Sources/ImageEncoding.swift, Sources/ImageProcessing.swift, Tests/ImageEncoderTests.swift
A prerequisite for [#227 Caching Processing Image](https://github.com/kean/Nuke/pull/227).
Nuke currently provides image decoding infrastrucure: `ImageDecoding`, `ImageDecoder`, `ImageDecoderRegistry`. But it would now also need to be able to encode processed images. In order to to that we add and the new procotol:
```swift
public protocol ImageEncoding {
func encode(image: Image) -> Data?
}
```
We also provide a default implementation of `ImageEncoding` protocol – `ImageEncoder` which uses `PNG` for images with transparency and `JPEG` for opaque images.
In order to decide which encoder to use for each image, we are going to need new infrastructure similar to the one which we use for selecting decoders.
- [Nuke 8.1] Add support for HEIF
=> Image Encoders

Demo/Sources/ProgressiveDecodingDemoViewController.swift, Demo/Sources/RateLimiterDemoViewController.swift, Sources/ImagePipeline.swift, Sources/ImageProcessing.swift, Sources/ImageRequest.swift, Sources/ImageView.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineProgressiveDecodingTests.swift, Tests/ImagePipelineTests.swift, Tests/ImagePreheaterTests.swift, Tests/ImageProcessingTests.swift, Tests/ImageRequestTests.swift, Tests/ImageViewTests.swift, Tests/NukeExtensions.swift, Tests/PerformanceTests.swift
- Move advanced options into separate `ImageRequestOptions` struct
- Remove the entire zoo of processing API, leaves a single one - `processors: [ImageProcessing]`
- Initializers now accept every single option that request might have
Settings processor:
```swift
let request = ImageRequest(url: URL(string: "http://..."), processors: [
ImageProcessor.Resize(size: CGSize(width: 44, height: 44))
])
```
Setting priority:
```swift
let request = ImageRequest(url: URL(string: "http://..."), priority: .high)
```
Setting everything:
```swift
let request = ImageRequest(
url: URL(string: "http://..."),
processors: [
ImageProcessor.Resize(size: CGSize(width: 44, height: 44), crop: true),
ImageProcessor.RoundedCorners(radius: 16)
],
priority: .high,
options: .init(
memoryCacheOptions: .init( …
```
=> Rework ImageRequest

Nuke.xcodeproj/project.pbxproj, Sources/ImageDecoding.swift, Sources/ImageEncoding.swift, Sources/ImagePipeline.swift, Sources/ImagePipelineConfiguration.swift, Sources/ImageProcessing.swift, Tests/Helpers.swift, Tests/ImageDecoderRegistryTests.swift, Tests/ImagePipelineDataCachingTests.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineTests.swift, Tests/ImageProcessingTests.swift, Tests/ImageViewTests.swift, Tests/MockImageProcessor.swift
- As a user, I would like to store processed images on disk, not the original ones, because recreating the processed ones is expensive and storing the original ones is wasteful
- As a user, I would like to store both processed and original images on disk so that I could create different variations of the same image by applying different processors, on demand
Extend `ImagePipeline` to support caching processed images and allow users to configure the pipeline to store only the original image data, or only the processed image data, or both.
The are multiple prerequisites for making this work.
Decompression is currently part of image processing which it shouldn't be because now in the case when we have processed image data, we will need to decompress it but we won't need to process it again. …
=> Caching Processed Images

Sources/ImagePipeline.swift, Sources/ImagePipelineConfiguration.swift, Sources/Task.swift, Tests/ImagePipelineDeduplicationTests.swift
- Add `isProcessingDeduplicationEnabled` option:
`false` by default. An experimental feature. When enabled, pipeline
will avoid any duplicated work when processing images. For example,
let't take this two requests:
```swift
let url = URL(string: "http://example.com/image")
pipeline.loadImage(with: ImageRequest(url: url, processors: [
ImageProcessor.Resize(size: CGSize(width: 44, height: 44)),
ImageProcessor.GaussianBlur(radius: 8)
]))
pipeline.loadImage(with: ImageRequest(url: url, processors: [
ImageProcessor.Resize(size: CGSize(width: 44, height: 44))
]))
```
Nuke will load the image data only once, resize the image once and
apply the blur also only once. There is no duplicated work done at
any stage.
- WARNING: When enabled each intermediate processed image will be
stored in disk data …
=> Deduplicating Processing Tasks (Experimental)

README.md, Sources/ImagePipeline.swift, Sources/ImageTask.swift, Tests/ImagePipelineDataCachingTests.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineTests.swift
```swift
// Before
task.setPriority(.high)
// After
task.priority = .high
print(task.priority) // You can now read the current priority
```
=> Add ImageTask priority property to replace setPriority method

Sources/ImagePipeline.swift, Sources/ImagePipelineConfiguration.swift, Sources/ImageProcessing.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImageProcessingTests.swift, Tests/PerformanceTests.swift
Enable processing deduplication by default
- Enable processing deduplication by default
- Remove `isProcessingDeduplicationEnabled` option from `ImagePipeline.Configuration`
- Make `ImageProcessor.Composition` public
=> Enable processing deduplication by default

Nuke.xcodeproj/project.pbxproj, Sources/Deprecated.swift, Sources/ImageDecoding.swift, Sources/ImagePipeline.swift, Sources/ImageProcessing.swift, Sources/ImageTask.swift, Tests/ImagePipelineDataCachingTests.swift, Tests/ImagePipelineTests.swift
Add all of the APIs deprecated in Nuke 8 to ease the migration.
=> Add deprecated APIs

Demo/Sources/AnimatedImageUsingVideoViewController.swift, Demo/Sources/AnimatedImageViewController.swift, Demo/Sources/BasicDemoViewController.swift, Demo/Sources/PrefetchingDemoViewController.swift, Demo/Sources/ProgressiveDecodingDemoViewController.swift, Demo/Sources/RateLimiterDemoViewController.swift, Documentation/Guides/Performance Guide.md, Nuke.xcodeproj/project.pbxproj, README.md, Sources/Deprecated.swift, Sources/ImageView.swift, Sources/ImageViewExtensions.swift, Tests/DeprecatedTests.swift, Tests/ImageViewIntegrationTests.swift, Tests/ImageViewTests.swift, Tests/PerformanceTests.swift, Tests/XCTestCase+Nuke.swift
- Future-proof Objective-C `ImageDisplaying` protocol by adding `nuke_` prefixes to avoid clashes in Objective-C runtime
- Add `imageView.nk.setImage(with:)` family of methods as a replacement for `Nuke.loadImage(with:into:)`. The latter wasn't grammatically correct, that's the first. `setImage(with:)` methods are also more conventional.
- Add `WKInterfaceImage` support
- Add `DeprecatedTests` to make sure that all deprecated methods work exactly as they were in the previous versions
=> Improve image view extensions

Sources/ImageCache.swift, Sources/ImagePipeline.swift, Sources/ImagePreheater.swift, Sources/ImageRequest.swift, Tests/DeprecatedTests.swift, Tests/ImageRequestTests.swift
- Add `filteredURL` option to `ImageRequestOptions`
In some cases your image URLs might contains transient query parameters like access tokens which must be ignored when generating cache keys. If that's the case, set this property to a URL without the unwanted fields:
```swift
let request = ImageRequest(
url: URL(string: "http://example.com/image.jpeg?token=1")! ,
options: .init(filteredURL: "http://example.com/image.jpeg")
)
```
This option affects both memory and disk caches.
-  Refactor the way cache and load keys are created and used
=> Improve cache and load keys support

Sources/Deprecated.swift, Sources/ImageDecoding.swift, Sources/ImageEncoding.swift, Sources/ImageProcessing.swift, Tests/Helpers.swift, Tests/ImageProcessingTests.swift
- Refactor existing processors by introducing `CGSize`, `CGImage`, `Image` and other extensions
- Add new `ImageProcessor.Crop` and fix some issues in the previous implementation
- Make `ImageProcessor.Resize` and `ImageProcessor.Crop` available on macOS
- Add nice `CustomStringConvertible` implementations for each image processor
- Add documentation for image processors
=> Refactor image processing

Demo/Sources/ProgressiveDecodingDemoViewController.swift, Nuke.xcodeproj/project.pbxproj, README.md, Sources/DataCache.swift, Sources/Deprecated.swift, Sources/ImagePipeline.swift, Sources/ImageRequest.swift, Sources/ImageTask.swift, Sources/ImageViewExtensions.swift, Tests/ImagePipelineDeduplicationTests.swift, Tests/ImagePipelineProgressiveDecodingTests.swift, Tests/ImagePipelineResumableDataTests.swift, Tests/ImagePipelineTests.swift, Tests/ImageViewTests.swift, Tests/MockDataLoader.swift, Tests/MockImagePipeline.swift, Tests/PerformanceTests.swift
Revert the addition of `ImageTaskDelegate` because this change of the primary public API and the increased complexity were not worth the performance improvements.
=> Remove image task delegate

Sources/ImageDecoding.swift
There was a defect in iOS 9 which made `UIImage` initializer not thread safe and which was fixed in iOS 10. The workaround is no longer needed.
It is now also possible to decode images in parallel.
More information available here https://github.com/AFNetworking/AFNetworking/issues/2572.
=> Remove no longer needed synchronization point in ImageDecoder

Sources/DataCache.swift, Sources/ImagePipeline.swift, Sources/ImagePreheater.swift
These changes configure access queues to target system queues. I have written about this [recently](https://troubled.pro/2019/07/mutex.html), it is to control thread creation. 
The quality of service configuration I’m suggesting performs particularly well in my setup. I have also tried setting QoS for Nuke’s operation queues, but didn’t accomplish any palpable performance gains.
=> Target system queues

Sources/DataLoader.swift
This is a proposed resolution to #260
I would point out that the following warning is emitted on Xcode versions lower than 11.0, but this does not prevent compilation:
> Unknown target environment for build configuration 'targetEnvironment'
=> Add Support for Mac Catalyst

Sources/ImagePipeline.swift, Sources/ImagePipelineConfiguration.swift, Sources/ImageTask.swift, Sources/ImageViewExtensions.swift, Tests/ImagePipelineConfigurationTests.swift, Tests/ImagePipelineTests.swift, Tests/MockImagePipeline.swift
- Add an option to configure callback queue on the pipeline level via `ImagePipeline.Configuration`
- Add an option to configure callback queue on individual request level
=> Add two options to configure callback queues

Sources/ImagePipeline.swift, Sources/Task.swift, Tests/TaskTests.swift
- Remove `Task.Job` and add `Task.Publisher`. The split of responsibilities should now be clear for everyone familiar with `Combine` or other reactive framework.
=> Refactor Task

Sources/DataLoader.swift
As returned from the Linter. This simply replaces () with Void where needed.
=> Fix Void Return Violation

Sources/ImagePipeline.swift, Sources/ImageViewExtensions.swift, Sources/Internal.swift
Make `ImagePipeline` more readable by splitting it into separate extensions and also extracting all logging code into a separate component.
=> ImagePipeline Cleanup

Sources/Deprecated.swift, Sources/ImageCache.swift, Sources/ImageDecoding.swift, Sources/ImageEncoding.swift, Sources/ImageProcessing.swift, Sources/ImageTask.swift, Sources/ImageViewExtensions.swift
Deprecate Image to avoid name clashes with SwiftUI, add PlatformImage as a replacement
=> Deprecate Image

Sources/ImageProcessing.swift
The `RoundedCorners` image processor has an existing `Border` parameter. However It was not respecting the `border.width` when drawing the stroke. The stoke was always drawn with a width of 1.
This PR corrects the width of the stroke border in the `RoundedCorners` processor. 
This PR also adds an optional `border` parameter to the `Circle` processor. The new parameter defaults to `nil` in order to prevent a breaking API change.
=> RoundedCorners and Circle image processor Border width

Nuke.xcodeproj/project.pbxproj, Sources/DataLoader.swift, Sources/ImagePipeline.swift, Sources/ImagePipelineConfiguration.swift, Sources/ImageTask.swift, Tests/ImagePipelineEventsTests.swift, Tests/ImagePipelineProcessorTests.swift, Tests/MockImagePipeline.swift, Tests/MockImageProcessor.swift, Tests/NukeExtensions.swift, Tests/XCTestCase+Nuke.swift, Tests/XCTestCaseExtensions.swift
- Logging
```
LocalDataTask <B6C07A0C-7E8E-4E3D-9727-56887E5232B2>.<27> resumed
LocalDataTask <B6C07A0C-7E8E-4E3D-9727-56887E5232B2>.<27> receivedResponse(response: <NSHTTPURLResponse: 0x600001f9dd60> { URL: https://cloud.githubusercontent.com/assets/1567433/9781961/f3d865de-57a1-11e5-87fd-bb8f28515a16.jpg } { Status Code: 200, Headers {
LocalDataTask <B6C07A0C-7E8E-4E3D-9727-56887E5232B2>.<27> receivedData(data: 32038 bytes)
LocalDataTask <B6C07A0C-7E8E-4E3D-9727-56887E5232B2>.<27> completed(error: nil)
```
- Monitoring download speed https://github.com/kean/Nuke/issues/313
=> Add DataLoader and ImagePipeline events

Documentation/Migrations/Nuke 8 Migration Guide.md
As titled, I found a syntax typo `cae` in the migration guide, and also update indentations to make it consistent.
=> Align code formatting of Nuke 8 migration guide

Sources/DataCache.swift, Sources/ImagePipeline.swift, Tests/DataCacheTests.swift
This PR realizes the original vision for `DataCache`.
- Reimplement staging/flushing mechanism which now performs flushes on certain intervals instead of on every write. This gives more control to the component and makes empty flushes instantaneous. It is also theoretically faster, but it's not something that I measured or wanted to optimize.
- Add public property `let queue: DispatchQueue`
- Add public method `func url(for key: Key) -> URL?`
- `flush` not performs synchronously
- Add `flush(for:)` methods which allows to flush changes on disk only for the given key
This PR also adds a new API to `ImagePipeline`:
- `func cacheKey(for request: ImageRequest, isProcessedData: Bool = false) -> String`
=> DataCache Improvements

README.md, Sources/ImageEncoding.swift
- Add a new `ImageEncoders` "namespace"
- Add `ImageEncoders.ImageIO`- an [Image I/O](https://developer.apple.com/documentation/imageio) based encoder with support for HEIF
- Add an experimental `ImageEncoder._isHEIFPreferred` option to `ImageEncoder` which automatically switches to HEIF when it is available. HEIF can save up to 50% space on disk compared to JPEG
- The default adaptive encoder now uses `ImageEncoders.ImageIO` under the hood
=> Add ImageIO Encoder and HEIF Support

Nuke.xcodeproj/project.pbxproj, README.md, Sources/ImageDecoding.swift, Sources/ImageTask.swift, Tests/ImagePipelineDecodingTests.swift
- Add new experimental `_ImageDecoding` protocol
```swift
public protocol _ImageDecoding: ImageDecoding {
func decode(data: Data) -> ImageContainer?
func decodeProgressively(data: Data) -> ImageContainer?
}
```
- Add `ImageContainer` type which contains image along with associated image data (optional, depends on decoder), and user info.
- Add SVG example in README
- Add `ImageDecoders.Empty`
> All change are fully backward comparably, nothing is deprecated
=> Add new _ImageDecoding infrastructure

Nuke.xcodeproj/xcshareddata/xcschemes/Nuke Unit Tests.xcscheme, Sources/Internal.swift
=> Fixing Nuke.Operation TSan issues with non atomic properties.

Sources/ImageCache.swift, Tests/ImageCacheTests.swift
Use DispatchSourceMemoryPressure instead of UIApplication.didReceiveMemoryWarningNotification. This should work in other targets then iOS and tvOS as well.
Unfortunately I'm not sure how to cover this in a test. Maybe it would be better to use it only on other targets and keep the current implementation on iOS/tvOS
=> Use DispatchSourceMemoryPressure

README.md, Sources/ImageViewExtensions.swift, Tests/ImageViewTests.swift
When retrieving icons from the cloud, it's useful to set tint colours to them based on the app theme. I've made the assumption if tint colours are set, then rendering mode must be set to `.alwaysTemplate` which I think is a fair assumption? Looking forward to hearing your thoughts or if there's a better place to implement this.
=> Add tint colors to ImageLoadingOptions

Sources/ImagePipeline.swift, Sources/Task.swift, Tests/ImagePipelineTests/ImagePipelineTests.swift, Tests/TaskTests.swift
A task can be synchronously terminated by its `starter` block during a call to Task.subscribe(), for instance when the result is cached. This in turn causes ImagePipeline's startImageTask/startDataTask to retain the task and subscription in the `tasks` dictionary indefinitely.
This fix changes Task.subscribe() to return nil if the task is terminated before the method returns. This appears to be in line with the documented intent for the method, and resolves the issue.
=> Fix a bug where ImagePipeline.loadImage could retain its completion block indefinitely

Sources/ImageViewExtensions.swift
Hi! Looks like the referenced bug was fixed long ago. So, here it is - `unowned imageView`
I'm not sure if it changes any performance characteristics but theoretically, it should, right?
=> Make imageView unowned in ImageViewController

Documentation/Migrations/Nuke 9 Migration Guide.md
Looks like the link to release notes is broken for pointing at `9.0-beta.2` instead of `9.0.0-beta.2`. Anyways, it seems like this should be pointing at `9.0.0` now.
=> Fix broken link in Nuke 9 Migration Guide

Sources/ImageCache.swift
Fixes an issue introduced in #370 where caches are cleared when the memory pressure changes to a `normal` level.
Limits image cache clearing to `warning` and `critical` memory pressure level changes.
=> Fix cache memory pressure monitoring

CHANGELOG.md, Sources/ImagePipeline.swift, Sources/ImageRequest.swift, Sources/ImageViewExtensions.swift
- Add `ImageRequestConvertible` to reduce the API area and remove duplicated documenation
=> Add ImageRequestConvertible

Sources/ImageProcessing.swift, Tests/ImageProcessorsTests/RoundedCornersTests.swift
- Make `ImageProcessors.Circle` and `ImageProcessors.RoundedCorners` available on macOS
- Remove public `CGSize: Hashable` conformance
=> Make ImageProcessors.Circle and ImageProcessors.RoundedCorners available on macOS

README.md, Sources/ImagePipeline.swift, Sources/ImageRequest.swift, Tests/ImagePipelineTests/ImagePipelineDataCachingTests.swift, Tests/ImagePipelineTests/ImagePipelineTests.swift, Tests/ImageViewTests.swift, Tests/MockDataCache.swift
Add an option to keep the images in cache, but instruct the pipeline to ignore the cached data.
```swift
let request = ImageRequest(url: url, cachePolicy: .reloadIgnoringCacheData)
Nuke.loadImage(with: request, into: imageView)
```
=> Add ImageRequest.CachePolicy

Sources/ImageViewExtensions.swift
At the moment, for working with Nuke in macOS, all views need to be a subclass of `NSView`. This is because the `ImageDisplayingView` enforces that constraint, which however is not needed for Caching purposes (the main reason I'm using Nuke). 
Hence, I have removed the `NSView` requirement and used `NSObject` instead, so that it works with `NSCell`, `NSTextAttachment` and other types which can display images but do not inherit from `NSView`. To make the animation work in layer based views, I have added a `Nuke_Animating` protocol only for macOS.
=> macOS: Remove requirement of NSView 

Sources/ImageRequest.swift, Sources/Tasks/TaskLoadImageData.swift, Tests/ImagePipelineTests/ImagePipelineDataCachingTests.swift
This new policy works similar to `URLRequest` [cachePolicy](https://developer.apple.com/documentation/foundation/urlrequest/cachepolicy) with the same name but will work with the custom data cache that you provide using `ImagePipeline.Configuration`. It covers a couple of scenarios that currently are unnecessarily hard to implement using Nuke.
=> Add ImageRequest.CachePolicy.returnCacheDataDontLoad

Nuke.xcodeproj/project.pbxproj, Sources/ImagePipeline.swift, Tests/ImagePublisherTests.swift, Tests/MockDataLoader.swift
- Add "Low Data Mode" tests for `ImagePublisher`
- Add convenience `dataLoadingError` property to `ImagePipeline.Error`
- Document "Low Data Mode" in [Nuke Docs](https://kean.blog/nuke/guides/combine)
=> Add Low Data Mode

Nuke.xcodeproj/project.pbxproj, Sources/Deprecated.swift, Sources/ImageCache.swift, Sources/ImagePipeline.swift, Sources/ImagePipelineCache.swift, Sources/ImagePublisher.swift, Sources/ImageViewExtensions.swift, Sources/Tasks/TaskLoadImage.swift, Sources/Tasks/TaskProcessImage.swift, Tests/ImagePipelineCacheTests.swift, Tests/ImagePipelineTests/ImagePipelineDataCachingTests.swift, Tests/ImagePipelineTests/ImagePipelineProcessorTests.swift, Tests/ImagePipelineTests/ImagePipelineTests.swift, Tests/MockImageCache.swift
- `ImageCaching` (now `MemoryCaching`) now works with `ImageCacheKey` (an opaque container) instead of `ImageRequest`. If you are providing a custom implementation of the `MemoryCaching` protocol, it needs to be updated accordingly.
- Add initial `ImagePipeline.Cache` implementation to give users more high-level APIs for dealing with cache layers in the pipeline
=> Add initial ImagePipeline.Cache implementation

Nuke.xcodeproj/project.pbxproj, Sources/Deprecated.swift, Sources/ImagePipeline.swift, Sources/ImagePipelineConfiguration.swift, Sources/ImagePrefetcher.swift, Sources/Tasks/ImagePipelineTask.swift, Sources/Tasks/Task.swift, Sources/Tasks/TaskLoadImage.swift, Sources/Tasks/TaskLoadImageData.swift, Tests/ImagePipelineTests/ImagePipelineDataCachingTests.swift, Tests/ImagePipelineTests/ImagePipelineDeduplicationTests.swift, Tests/MockDataCache.swift, Tests/MockDataLoader.swift, Tests/MockImageEncoder.swift, Tests/TaskTests.swift
Add `DiskCachePolicy` that replaces `DataCacheOptions.storedItems`. The new policy fixes some of the inefficiencies of the previous model and provides more control. The main addition is an `.automatic` policy, which is also a default. The policy is: for requests with processors, it encodes and stores processed images; for requests with no processors, store original image data.
=> Add DiskCachePolicy

Sources/ImageRequest.swift, Sources/Internal/Extensions.swift, Sources/Tasks/TaskLoadImage.swift, Sources/Tasks/TaskLoadImageData.swift, Tests/ImagePipelineTests/ImagePipelineDataCachingTests.swift
The pipeline now automatically doesn't store images fetched using file:// and data:// schemes in the disk cache
=> Avoid storing local files in disk cache

Sources/ImageDecoding.swift, Sources/ImagePipelineCache.swift, Sources/ImagePublisher.swift, Sources/ImageTask.swift, Sources/ImageViewExtensions.swift, Sources/Tasks/TaskFetchDecodedImage.swift, Sources/Tasks/TaskLoadImage.swift, Tests/Helpers.swift, Tests/ImagePipelineTests/ImagePipelineImageCacheTests.swift
Addresses https://github.com/kean/Nuke/issues/435 and https://github.com/kean/Nuke/issues/361. Next step is also to keep track of some cache metrics, like hit/miss count.
=> Cache Type

Nuke.xcodeproj/project.pbxproj, Sources/Core/ImagePipeline.swift, Sources/Core/ImageRequest.swift, Sources/Internal/Combine.swift, Sources/Internal/ResumableData.swift, Sources/Internal/Tasks/TaskFetchOriginalImageData.swift, Sources/Internal/Tasks/TaskFetchWithPublisher.swift, Tests/CombineExtensions.swift, Tests/ImagePipelineTests/ImagePipelinePublisherTests.swift, Tests/ImageRequestTests.swift
Example with the Photos framework:
```swift
let request = ImageRequest(
id: asset.localIdentifier,
data: PHAssetManager.imageDataPublisher(for: asset)
)
```
Example with Data:
```swift
let request = ImageRequest(
id: "image-01",
data: Just(Data())
)
```
=> Add Publisher<Data> support to  ImageRequest

Sources/UI/ImageViewExtensions.swift
Thank you for the nice update to version10!!
I wanna suggest one change. nuke_display(image:data) which is a protocol method of Nuke_ImageDisplaying is defined as extension method of UIImageView, NSImageView and WKInterfaceImage. But, the data parameter is never used although this can be the destructive change at updating to version10.
So, if there are not some hesitations for this point, it is better to have default parameter nil, I think.
=> Add: default parameter nil to nuke_display(image:data:)

Sources/Combine/ImagePublisher.swift
This PR moves around the logic of the Nuke ImagePublisher to only emit when demand is requested. Emitting otherwise can potentially lead to unexpected crashing, specifically in the case of returning caching images. The previous logic would emit a cached value immediately after sending the subscription to subscribers, and would sometimes crash if the value was sent before the subscribers could fully subscribe.
The approach used here was influenced by articles such as [this](https://medium.com/flawless-app-stories/swift-combine-custom-publisher-6d1cc3dc248f) and [this](https://www.swiftbysundell.com/articles/building-custom-combine-publishers-in-swift/#keeping-up-with-demand).
=> Improved runtime safety of ImagePublisher

Nuke.xcodeproj/project.pbxproj, Sources/Core/ImageDecoding.swift, Sources/Core/ImagePipeline.swift, Sources/Core/ImagePipelineConfiguration.swift, Sources/Core/ImageProcessing.swift, Sources/Core/ImageRequest.swift, Sources/Core/ImageResponse.swift, Sources/Internal/ImageRequestKeys.swift, Tests/ImagePipelineTests/ImagePipelineCoalescingTests.swift, Tests/ImagePipelineTests/ImagePipelineDataCacheTests.swift, Tests/ImagePipelineTests/ImagePipelineImageCacheTests.swift, Tests/ImagePipelineTests/ImagePipelineTests.swift, Tests/ImageProcessorsTests/ImageDownsampleTests.swift
Fully supports caching and task coalescing
=> Add an API for retrieving image thumbnails

Sources/Core/Loading/DataLoader.swift
Add URLSession & URLSessionDataTask descriptions so when using the XCode 13 network debug tool, it will be easy to group and identify API calls made by Nuke.
See [Analyze HTTP traffic in Instruments](https://developer.apple.com/wwdc21/10212) video from WWDC21.
=> Add URLSession & URLSessionDataTask descriptions

Sources/Core/ImagePipeline.swift, Sources/UI/FetchImage.swift, Tests/ImagePipelineTests/ImagePipelineAsyncAwaitTests.swift
This will be merged when it's clear what to do with https://github.com/kean/Nuke/issues/526
Add the following async/await APIs:
```swift
extension ImagePipeline {
public func loadImage(with request: ImageRequestConvertible) async throws -> ImageResponse
public func loadData(with request: ImageRequestConvertible) async throws -> (Data, URLResponse?)
}
extension FetchImage {
public func load(_ action: @escaping () async throws -> ImageResponse)
}
```
=> Add async/await

Sources/Core/ImagePipeline.swift, Sources/Core/Tasks/TaskFetchDecodedImage.swift, Tests/ImagePipelineTests/ImagePipelineTests.swift
=> Add associated Data to ImagePipeline.Error.decodingFailed

Documentation/Migrations/Nuke 11 Migration Guide.md, Sources/Core/Processing/ImageProcessing.swift, Sources/Core/Processing/ImageProcessors+Anonymous.swift, Sources/Core/Processing/ImageProcessors+Circle.swift, Sources/Core/Processing/ImageProcessors+Composition.swift, Sources/Core/Processing/ImageProcessors+CoreImage.swift, Sources/Core/Processing/ImageProcessors+GaussianBlur.swift, Sources/Core/Processing/ImageProcessors+Resize.swift, Sources/Core/Processing/ImageProcessors+RoundedCorners.swift, Tests/MockImageProcessor.swift, Tests/NukeExtensions.swift
Simplify two-method `ImageProcessing` setup:
```swift 
public protocol ImageProcessing {
// Remove
func process(_ image: PlatformImage) -> PlatformImage?
// This method is now required
func process(_ container: ImageContainer, context: ImageProcessingContext) -> ImageContainer?
// ...
}
```
The two-method setup was created to avoid breaking changes in an already packed [Nuke 9.0](https://github.com/kean/Nuke/releases/tag/9.0.0) release. But it ended-up being a bit overcomplicated. It's not obvious which method to implement without reading the documentation. And if you implement a more "advanced" method with `ImageContainer`, you have to also implement a "basic" one:
```swift
struct CustomProcessor: ImageProcessing {
func process(_ image: PlatformImage) -> PlatformImage? {
// What do you …
```
=> Draft: Simplify ImageProcessing

Documentation/Migrations/Nuke 11 Migration Guide.md, Sources/Core/ImagePipeline.swift, Sources/Core/ImageResponse.swift, Sources/Core/Processing/ImageProcessing.swift, Sources/Core/Processing/ImageProcessors+Anonymous.swift, Sources/Core/Processing/ImageProcessors+Circle.swift, Sources/Core/Processing/ImageProcessors+Composition.swift, Sources/Core/Processing/ImageProcessors+CoreImage.swift, Sources/Core/Processing/ImageProcessors+GaussianBlur.swift, Sources/Core/Processing/ImageProcessors+Resize.swift, Sources/Core/Processing/ImageProcessors+RoundedCorners.swift, Sources/Core/Processing/ImageProcessors.swift, Sources/Core/Tasks/OperationTask.swift, Sources/Core/Tasks/TaskLoadImage.swift, Sources/Internal/Graphics.swift, Sources/Internal/Log.swift, Tests/ImageEncoderTests.swift, Tests/ImageProcessorsTests/AnonymousTests.swift, Tests/ImageProcessorsTests/CompositionTests.swift, Tests/ImageProcessorsTests/CoreImageFilterTests.swift, Tests/ImageProcessorsTests/GaussianBlurTests.swift, Tests/MockImageProcessor.swift, Tests/NukeExtensions.swift
`ImageProcessing` protocol is now throwing:
```swift
public protocol ImageProcessing {
// Before (Nuke 10)
func process(_ container: ImageContainer, context: ImageProcessingContext) -> ImageContainer?
// After (Nuke 11)
func process(_ container: ImageContainer, context: ImageProcessingContext) throws -> ImageContainer
}
```
With this change you can now capture and easily analyze processing errors.
There are a couple of other related changes to the public API:
- `CoreImageFilter.apply(filter:to:)` is now throwing an returns non-optional value.
- Make `CoreImageFilter` properties `name` and `parameters` public.
- Add `ImageDrawingError`
=> Throwing Image Processing

Sources/Core/ImageRequest.swift, Sources/Core/Pipeline/ImagePipelineConfiguration.swift, Sources/Core/Tasks/TaskFetchOriginalImageData.swift, Sources/Core/Tasks/TaskFetchWithPublisher.swift, Sources/Internal/Log.swift, Tests/ImagePipelineTests/ImagePipelineTests.swift
Add the following option to ignore data loading queue:
```swift
// For entire pipeline
extension ImagePipeline.Configuration {
/// `false` by default. Set it to false to perform all data loading
/// operations immediatelly, ignoring `dataLoadingQueue`.
public var isDataLoadingQueueSkipped = false
}
// For individual requests
extension ImageRequest.Options {
/// Perform data loading immediatelly, ignoring `dataLoadingQueue`.
///
/// - warning: If there is an outstanding task for loading the same
/// resource but without this option, a new task will be created.
public static let skipDataLoadingQueue = Options(rawValue: 1 << 5)
}
```
Use-case:
- Using a data loader or data publisher that limits concurrent tasks in a different way or doesn't require it
- Elevating the priority of critical …
=> Skip data loading queue

Sources/Core/Tasks/TaskFetchDecodedImage.swift, Sources/Core/Tasks/TaskFetchOriginalImageData.swift, Sources/Core/Tasks/TaskFetchWithPublisher.swift, Tests/ImagePipelineTests/ImagePipelinePublisherTests.swift
Enable disk cache (`DataCaching`) for data publishers:
```swift
let request = ImageRequest(id: "a", data: Just(Test.data))
```
There are a few options to disable it:
- Create a pipeline with no disk cache (default behavior)
- Implement `ImagePipelineDelegate` method `dataCache(for:pipeline:)` or `willCache(data:image:for:pipeline:)` and disable cache on per-request basis
- Pass `.disableDiskCacheWrites` option to requests backed by data publishers
=> Enable custom disk cache for data publishers

Sources/Nuke/Core/ImageTask.swift, Sources/Nuke/Core/Pipeline/ImagePipeline.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineAsyncAwaitTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineProgressiveDecodingTests.swift
Represent progressive decoding using async sequence:
```swift
for try await response in pipeline.images(for: Test.request) {
print("Got new response: \(response)")
}
```
Update `progress` closure to only be called when download progress is updated, not when a new preview is returned.
=> Progressive Decoding with AsyncThrowingStream

Documentation/Migrations/Nuke 11 Migration Guide.md, Sources/Nuke/Processing/ImageProcessing.swift, Sources/Nuke/Processing/ImageProcessors+Circle.swift, Sources/Nuke/Processing/ImageProcessors+Composition.swift, Sources/Nuke/Processing/ImageProcessors+GaussianBlur.swift, Sources/Nuke/Processing/ImageProcessors+Resize.swift, Sources/Nuke/Processing/ImageProcessors+RoundedCorners.swift
`ImageProcessing` types that implement `Hashable` protocol now get default `hashableIdentifier` implementation
=> Default hashableIdentifier for ImageProcessing

Nuke.xcodeproj/project.pbxproj, Sources/Nuke/ImageTask.swift, Sources/Nuke/Pipeline/ImagePipeline.swift, Sources/Nuke/Pipeline/ImagePipelineDelegate.swift, Tests/ImagePipelineObserver.swift, Tests/NukeExtensions.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineAsyncAwaitTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineDelegateTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineTaskDelegateTests.swift
There are currently two mechanisms for receiving image tasks events: `ImagePipelineDelegate` with a top-level `ImageTaskEvent` and the new `ImageTaskDelegate` added for Async/Await. The goal is to consolidate these two mechanisms, similar to how `URLSessionDelegate` work.
=> ImageTaskDelegate

Documentation/Migrations/Nuke 11 Migration Guide.md, Documentation/Switch/switch-from-kingfisher.md, Documentation/Switch/switch-from-sdwebimage.md, README.md, Sources/Nuke/ImageRequest.swift, Sources/Nuke/Internal/Deprecated.swift, Sources/Nuke/Nuke.docc/Essentials/getting-started.md, Sources/Nuke/Nuke.docc/Extensions/ImagePipeline-Extension.md, Sources/Nuke/Nuke.docc/Performance/Caching/accessing-caches.md, Sources/Nuke/Nuke.docc/Performance/prefetching.md, Sources/Nuke/Pipeline/ImagePipeline.swift, Sources/Nuke/Pipeline/ImagePipelineCache.swift, Sources/Nuke/Prefetching/ImagePrefetcher.swift, Sources/NukeUI/FetchImage.swift, Sources/NukeUI/LazyImage.swift, Sources/NukeUI/LazyImageView.swift, Sources/NukeUI/NukeUI.docc/Extensions/FetchImage-Extensions.md, Sources/NukeUI/NukeUI.docc/Extensions/LazyImage-Extensions.md, Sources/NukeUI/NukeUI.docc/Extensions/LazyImageView-Extensions.md, Tests/NukeTests/ImagePipelineTests/ImagePipelineCacheTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelinePublisherTests.swift, Tests/NukeTests/ImagePrefetcherTests.swift
`ImageRequestConvertible` was originally introduced in [Nuke 9.2](https://github.com/kean/Nuke/releases/tag/9.2.0) to reduce number of versions of the `loadImage(:)` method in code completion, but it's no longer an issue with the new async/await APIs.
`ImageRequestConvertible` is soft-deprecated in Nuke 11. The other soft-deprecated APIs, such as a closure-based `ImagePipeline/loadImage(:)` will continue working with it. The new APIs, such as async/await `ImagePipeline/image(for:)` will work with `URL` and `ImageRequest` which is better for discoverability and performance.
If you are using `ImageRequestConvertible` in your code, consider removing it now. But it won't be officially deprecated until the next major release.
=> Update new APIs to not use ImageRequestConvertible

README.md, Sources/Nuke/Internal/Deprecated.swift, Sources/Nuke/Loading/DataLoader.swift, Sources/Nuke/Nuke.docc/Customization/LoadingData/loading-data.md, Sources/Nuke/Nuke.docc/Essentials/getting-started.md, Sources/Nuke/Nuke.docc/Extensions/DataLoader-Extension.md, Sources/NukeUI/Internal.swift, Tests/NukeTests/DataLoaderTests.swift
[Pulse 2.0](https://github.com/kean/Pulse) is optimized for working with images and now is a good time to provide a convenient way to integrate it with Nuke.
- Add `delegate: URLSessionDelegate?` property to `DataLoader` for observing network events
- Deprecated the existing `observer: DataLoaderObserving`
Pulse can now be integrated with a single line of code:
```swift
(ImagePipeline.shared.configuration.dataLoader as? DataLoader)?.delegate = URLSessionProxyDelegate()
```
The [demo project](https://github.com/kean/NukeDemo) was also updated to feature Pulse.
=> Add DataLoader delegate for easy Pulse integration

Sources/NukeUI/LazyImageView.swift
The example code for LazyImageView in the documentation still used the deprecated `source` attribute. This is a small fix to use the `url` attribute instead.
In the process of creating this PR I also came across two minor issues with the `onCompletion` closure, so I fixed those as well.
=> Update example code for LazyImageView

Sources/NukeUI/LazyImageView.swift
The placeholder view of a LazyImageView was hidden by default. The view is unhidden by the `load()` method, causing the placeholder to appear. However, that assumes that the loading process is started in the first place, which may not always be the case. Consider this example:
```swift
let imageView = LazyImageView()
imageView.url = item.imageURL // may be nil, depending on my data
```
When `item.imageURL` is nil, a request is never started, and therefore the placeholder view will never be unhidden.
With this PR, placeholder views are no longer always hidden when set, but instead this now depends on whether an image is already visible. If it is, the placeholder view will still be hidden, but if it isn't, the placeholder view will be visible.
Additionally, the `imageView` itself is now …
=> Show placeholder view of LazyImageView by default

Sources/Nuke/Caching/ImageCache.swift, Sources/Nuke/Pipeline/ImagePipeline.swift
Xcode 14.1RC shows warnings when withTaskCancellationHandler used with `handler` and `operation` arguments. This is a fix to call the renamed version without any warnings.
=> Update deprecated withTaskCancellationHandler

Sources/NukeUI/Image.swift, Sources/NukeUI/ImageView.swift, Sources/NukeUI/VideoPlayerView.swift
Changing the frame of a `LazyImage` that is rendering a video leads to an undesired animation while the `AVPlayerLayer` that drives `VideoPlayerView` is resized to its containing view. In changes here, I've added a configuration to disable the implicit animation associated with updating that layer's frame.
<details>
<summary>Reproducing sample project</summary>
```swift
import NukeUI
import SwiftUI
@main
struct Application: App {
var body: some Scene {
WindowGroup {
ContentView()
}
}
}
struct ContentView: View {
let url = URL(string: "https://media.tenor.com/o656qFKDzeUAAAPo/rick-astley-never-gonna-give-you-up.mp4")!
@State var scale: CGFloat = 0
var body: some View {
VStack {
let size = (scale + 1) * 150
LazyImage(url: url) { state in
state.image
}
.frame(width: size, height: size) …
```
=> Allow configuration of `CALayer` frame animations of the `VideoPlayerView`

Tests/NukeTests/ImageCacheTests.swift, Tests/NukeTests/ImageDecoderRegistryTests.swift, Tests/NukeTests/ImageProcessorsTests/ImageProcessorsProtocolExtensionsTests.swift
Hey @kean 👋 I've added some new tests that will increase the code coverage from 91.3% to 92.3% .
=> Add new tests

Sources/Nuke/Prefetching/ImagePrefetcher.swift
Call `didComplete` even when images are cached or when tried to prefetch empty list.
@kean sorry, seems to be fixed now + handled edge case when tried to load empty list.
=> `didComplete` edge cases.

.github/workflows/ci.yml, Sources/Nuke/Internal/Deprecated.swift, Sources/Nuke/Nuke.docc/Extensions/ImagePipeline-Extension.md, Sources/Nuke/Pipeline/ImagePipeline.swift, Sources/Nuke/Pipeline/ImagePipelineConfiguration.swift, Tests/NukeExtensions.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineConfigurationTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineLoadDataTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineProgressiveDecodingTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineTests.swift, Tests/NukeTests/ImagePrefetcherTests.swift, Tests/XCTestCase+Nuke.swift
Most of the APIs that use `ImageRequestConvertible` were originally deprecated in [Nuke 11.0](https://github.com/kean/Nuke/pull/567), except for a couple of methods in `ImagePipeline`. This PR fully deprecated `ImageRequestConvertible` so that it could be completely removed in the upcoming major release next year.
=> Fully deprecate previously soft-deprecated ImageRequestConvertible

.github/workflows/ci.yml, Sources/Nuke/Caching/DataCache.swift, Sources/Nuke/Internal/Deprecated.swift, Sources/Nuke/Nuke.docc/Performance/Caching/cache-layers.md, Tests/NukeTests/DataCacheTests.swift
Add `isCompressionEnabled` option to `DataCache` that enables compression using Apple’s [lzfse](https://en.wikipedia.org/wiki/LZFSE) algorithm offering an excellent balance between performance and compression ratio. It can reduce disk usage by up to 80%, allowing you to store many more images or reduce the cache size limit. By default, compression is disabled.
=> Data Cache Compression

Sources/NukeUI/Gifu/Classes/Animator.swift, Sources/NukeUI/ImageView.swift
The ImageView now tests if a gif is an animated gif, so that the animator only tries to animate it, if necessary. A static gif is rendered like any other image.
Previously, it was tried to animate every gif, whether it truly was animated or not. That resulted in no image being rendered at all.
=> Add the ability to render static gifs

Documentation/Nuke.docc/Performance/performance-guide.md, Nuke.xcodeproj/project.pbxproj, Sources/Nuke/ImageRequest.swift, Sources/Nuke/Internal/Graphics.swift, Sources/Nuke/Processing/ImageProcessingOptions.swift, Sources/Nuke/Processing/ImageProcessors+Resize.swift, Sources/Nuke/Processing/ImageProcessors.swift, Tests/NukePerformanceTests/ImageProcessingPerformanceTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineCoalescingTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineDataCacheTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineImageCacheTests.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineTests.swift, Tests/NukeTests/ImageProcessorsTests/ImageDownsampleTests.swift, Tests/NukeTests/ImageProcessorsTests/ResizeTests.swift
In the previous version, the only available option was `maxPixelSize`:
```swift
// Before
ImageRequest.ThumbnailOptions(maxPixelSize: 64)
```
The main issue with `maxPixelSize` is that it creates a thumbnail that _fits_ the target size. For example, if you have a wide image with `2000x400` pixel size and resize it to `maxPixelSize: 40`, the thumbnail will have the size `40x8` pixels. There was no way to create a `200x40` thumbnail, which is what you typically want to make sure the images have enough pixels to look good.
In addition to `init(maxPixelSize:)`, there is now a new initializer with the parameters that directly match `ImageProcessors.Resize`, so it's easy to switch between them.
```swift
// After
ImageRequest.ThumbnailOptions(size: CGSize(width: 64, height: 64), contentMode: …
```
=> Add more flexible target size options to ImageRequest.ThumbnailOptions

Nuke.xcodeproj/project.pbxproj, Sources/Nuke/Internal/DataPublisher.swift, Tests/NukeTests/DataPublisherTests.swift
Fix for the issue: https://github.com/kean/Nuke/issues/693.
`Future` is generally better approach than `PassthroughSubject` when you need to execute something once (e.g. network requests). What was failing in the original solution by the issue author is that `Future` starts execution right after creation as well, and needs to be wrapped in `Deferred` in order to start only after subscribing to it.
=> #693: DataPublisher created from async function should start lazily

Sources/NukeUI/LazyImage.swift
Resolves #710
Material.ultraThick is available on watchOS 10 and up, but it seemed like too much work to conditionally apply it
=> Fix NukeUI errors for watchOS

Sources/Nuke/Caching/Cache.swift, Sources/Nuke/Caching/DataCache.swift, Sources/Nuke/Internal/Extensions.swift
Removed unnecessary extension, because in iOS 8.0/macOS 10.10/tvOS 9.0/watchOS 2.0 it is already in the Foundation.
https://developer.apple.com/documentation/foundation/nslocking/4059821-withlock
All tests on all platforms were successful.
=> Remove useless extension

Documentation/NukeUI.docc/Extensions/FetchImage-Extensions.md
This pull request addresses a property name issue within FetchImage. Previously,
the code referenced a `view` property, which does not exist.
This has now been corrected to `image`, aligning with the existing properties within FetchImage.
Thank you again for your incredible work and commitment to this project.
=> Minor docs correction in FetchImage

Tests/NukeThreadSafetyTests/ThreadSafetyTests.swift
adds a test that shows https://github.com/kean/Nuke/issues/750
=> ThreadSafetyTests: add failing test where we load and store an image

Documentation/Nuke.docc/Customization/ImageFormats/supported-image-formats.md, Sources/Nuke/Caching/Cache.swift, Sources/Nuke/Decoding/AssetType.swift, Sources/Nuke/Decoding/ImageDecoders+Default.swift, Sources/Nuke/Internal/Graphics.swift, Sources/Nuke/Internal/ImagePublisher.swift, Sources/Nuke/Internal/LinkedList.swift, Sources/Nuke/Pipeline/ImagePipeline.swift, Sources/Nuke/Pipeline/ImagePipelineConfiguration.swift, Sources/Nuke/Prefetching/ImagePrefetcher.swift, Sources/Nuke/Tasks/AsyncTask.swift, Sources/Nuke/Tasks/OperationTask.swift, Sources/Nuke/Tasks/TaskFetchDecodedImage.swift, Sources/Nuke/Tasks/TaskFetchOriginalImageData.swift, Sources/Nuke/Tasks/TaskFetchWithPublisher.swift, Sources/Nuke/Tasks/TaskLoadData.swift, Sources/Nuke/Tasks/TaskLoadImage.swift, Sources/NukeExtensions/ImageViewExtensions.swift, Sources/NukeUI/FetchImage.swift, Sources/NukeUI/LazyImage.swift, Sources/NukeUI/LazyImageView.swift, Sources/NukeVideo/VideoPlayerView.swift, Tests/CombineExtensions.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineProgressiveDecodingTests.swift
if let shorthand syntax was introduced since swift 5.7. ([SE-3045](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md))
I replace codes by using following regexs.
regex | replacement
--- | --- 
if let (.+)? = \1 \{ | if let $1 {
if let (.+)? = \1, | if let $1,
if let (.+)? = self.\1 \{ | if let $1 {
if let (.+)? = self.\1, | if let $1,
=> Apply if let shorthand syntax

Sources/Nuke/Decoding/AssetType.swift
This PR removes trailing whitespace to resolve `trailing_whitespace` rule violation.
=> Remove trailing whitespace

Tests/NukeExtensionsTests/ImageViewIntegrationTests.swift
This PR fixes `ImageViewIntegrationTests.testLoadingWithNilURL()` because the test has failed.
Loading an image from an invalid URL should return a data loading error?
=> Fix image loading test

Sources/Nuke/Internal/Graphics.swift
Fixes https://github.com/kean/Nuke/issues/765.  The viral nature of concurrency unfortunately means that the blast radius is pretty high for just 2 warning fixes:
- Adds `@MainActor` to direct and downstream callers of `Screen.scale`
- Adds `@MainActor` to downstream callers in tests
- Moves `@MainActor` from XCTestCases to individual test functions instead
- Switches the image pipeline thread safety test from resizing to blurring.  This avoids marking the test as `@MainActor` which would destroy its ability to test threading.
=> Fix Xcode 15.3 concurrency warnings when using `Screen.scale`

Sources/Nuke/ImageRequest.swift
This PR fixes the raw value of `ImageRequest.UserInfoKey.thumbnailKey` to match the format with other keys.
=> Fix thumbnail key for image request

Sources/NukeUI/Internal.swift, Sources/NukeUI/LazyImageView.swift
I added `usePlaceholderAsFailure` because I think there are a lot of cases where people might want to keep the placeholder visible even if the image fails to load.
=> Add usePlaceholderAsFailure to show placeholder in case of image loading failure

CHANGELOG.md, Sources/Nuke/Pipeline/ImagePipelineConfiguration.swift, Sources/Nuke/Tasks/TaskFetchOriginalData.swift, Tests/NukeTests/ImagePipelineTests/ImagePipelineDataCacheTests.swift
An optimization that skips `DataLoader` when loading resources from local files.
=> Add isLocalResourcesSupportEnabled

Sources/Nuke/Loading/DataLoader.swift
Now that [Pulse uses task descriptions](https://github.com/kean/Pulse/pull/254), the Pulse console shows all Nuke network requests as the hard-coded `Nuke Load Data` value. 
~This PR appends the request description to the task description to differentiate the entries~ 
This PR removes the task description assignment.
=> Update task description

Sources/NukeExtensions/ImageViewExtensions.swift
Previously `runCrossDissolveWithContentMode` was adding the `transitionView` as a subview of the `imageView` and settting `imageView.alpha = 0`. This resulted in the image immediately disappearing since the `alpha` of subviews is multiplied by the `alpha` of super views.
This PR adds the `transitionView` to the `superview` of the `imageView` so the two image view's alphas are independent and properly cross-dissolve.
=> Correct fade transition when content modes differ

Sources/NukeExtensions/ImageViewExtensions.swift
This PR configures the cross-dissolve image transition view to more accurately mimic the original image view. It expands upon PR https://github.com/kean/Nuke/pull/786, which added the mimicking of view masking. Now, the tint color, symbol configuration, and preferred dynamic range values are also mimicked.
=> Improve cross dissolve transition accuracy

Sources/NukeExtensions/ImageViewExtensions.swift
Prevents an “unrecognized selector sent to instance” crash caused by UIKit incorrectly marking [`UIImageIVew.preferredImageDynamicRange`](https://developer.apple.com/documentation/uikit/uiimageview/4173133-preferredimagedynamicrange) available since iOS 2.0. Its actual availability is iOS 17.0+
The reference to `preferredImageDynamicRange` was added in https://github.com/kean/Nuke/pull/787 and released in Nuke v12.7.1
=> Fix “unrecognized selector sent to instance” crash in transition on iOS < 17
