kean/Nuke

- Nuke/Source/Core/ImageProcessor.swift
As asked in https://github.com/kean/Nuke/pull/42#issuecomment-160642586.
> Fix size rounding errors in image downscaling

- Sources/ImageLoadingView.swift
https://github.com/kean/Nuke/issues/70
> [Fix] Race condition with tasks not being cancelled

- Nuke.podspec
Stumbled upon this little typo when parsing my Acknowledgements. hth!
> Small typo

- Nuke.xcodeproj/project.pbxproj
- Nuke.xcodeproj/xcshareddata/xcschemes/Nuke iOS.xcscheme
- Nuke.xcodeproj/xcshareddata/xcschemes/Nuke macOS.xcscheme
- Nuke.xcodeproj/xcshareddata/xcschemes/Nuke tvOS.xcscheme
- Nuke.xcodeproj/xcshareddata/xcschemes/Nuke watchOS.xcscheme
- Sources/Cache.swift
- Sources/DataLoader.swift
- Sources/Loader.swift
- Tests/CacheTests.swift
- Tests/ManagerTests.swift
- Tests/RateLimiterTests.swift
- Tests/XCTestCaseExtensions.swift
I can understand not wanting to merge this into `master` until Xcode 9 is out of beta – you may want to make a `swift-4` branch that can become the base branch for this PR?
> Add Swift 4 support

- Nuke.podspec
- Nuke.xcodeproj/project.pbxproj
I ran the macOS test target and everything seemed fine... is there anything else I need to change?
> Lower the macOS deployment target to 10.10

- Sources/DataCache.swift
- Sources/ImagePipeline.swift
Hello.
First of all, congratulations for the framework and this great new version!
About the PR:
I know that it is planned the disk cache API opening, but I'm using a custom (and private) disk caching mechanism in my app, so I made some changes do allow this.
> Allow custom DataCaching implementation

- .swiftlint.yml
- Nuke.xcodeproj/project.pbxproj
- Sources/DataCache.swift
- Sources/DataLoader.swift
- Sources/ImageCache.swift
- Sources/ImageDecoding.swift
- Sources/ImagePipeline.swift
- Sources/ImagePreheater.swift
- Sources/ImageProcessing.swift
- Sources/ImageRequest.swift
- Sources/ImageTaskMetrics.swift
- Sources/ImageView.swift
- Sources/Internal.swift
- Tests/DataCacheTests.swift
- Tests/ImageCacheTests.swift
- Tests/ImagePipelineProgressiveDecodingTests.swift
- Tests/ImagePipelineResumableDataTests.swift
- Tests/MockDataLoader.swift
Add .swiftlint. It doesn't run automatically yet, it's just for internal use.
- Install SwiftLint using dependency manager
- Run SwiftLint on CI
> Integrate SwiftLint

- Sources/ImagePipeline.swift
- Sources/Task.swift
Since we now finally use  a holistic `Task`-based approach, we can start reusing more and more code. In this MR we remove all of the duplicated code which was used for reusing tasks between different image requests.
> Add TaskPool

- Demo/NukeDemo.xcodeproj/project.pbxproj
- Demo/Sources/AlamofireIntegrationDemoViewController.swift
- Demo/Sources/AnimatedImageUsingVideoViewController.swift
- Demo/Sources/AppDelegate.swift
- Demo/Sources/BasicDemoViewController.swift
- Demo/Sources/CustomCacheDemoViewController.swift
- Demo/Sources/DataCachingDemoViewController.swift
- Demo/Sources/Helpers/Utilities.swift
- Demo/Sources/ImagePipelineSettingsViewController.storyboard
- Demo/Sources/ImagePipelineSettingsViewController.swift
- Demo/Sources/MenuViewController.swift
- Demo/Sources/PrefetchingDemoViewController.swift
- Demo/Sources/ProgressiveDecodingDemoViewController.swift
- Demo/Sources/RateLimiterDemoViewController.swift
- LICENSE
Add a settings screen to configure ImagePipeline in runtime
> [Demo] Add ImagePipeline settings screen

- Demo/NukeDemo.xcodeproj/project.pbxproj
- Demo/Sources/BasicDemoViewController.swift
- Demo/Sources/ImagePipelineSettingsViewController.swift
- Demo/Sources/ImageProcessingDemoViewController.swift
- Demo/Sources/MenuViewController.swift
- Demo/Sources/ProgressiveDecodingDemoViewController.swift
- Sources/ImageProcessing.swift
> Add new Image Processing demo

- Sources/ImageProcessing.swift
For some use cases it makes sense to bake borders directly into the image. These changes add an optional border to `ImageProcessing.RoundedCorners`. I hope I’m not the only one who could use something like this.
> Draw border around rounded images

- .swiftlint.yml
- .travis.yml
- Demo/NukeDemo.xcodeproj/project.pbxproj
- Demo/NukeDemo.xcodeproj/xcshareddata/xcschemes/NukeDemo.xcscheme
- Demo/Podfile
- Demo/Podfile.lock
- Nuke.xcodeproj/project.pbxproj
- Nuke.xcodeproj/xcshareddata/xcschemes/Nuke.xcscheme
- Scripts/lint.sh
- Scripts/test.sh
- Scripts/validate_demo.sh
- Sources/Deprecated.swift
- Sources/ImageProcessing.swift
- Sources/ImageTask.swift
- Sources/ImageViewExtensions.swift
- Sources/Task.swift
- Run tests for multiple destinations in a single job
> Improve Travis setup

- .travis.yml
- Nuke.xcodeproj/xcshareddata/xcschemes/Nuke Performance Tests.xcscheme
- Tests/PerformanceTests.swift
Run performance tests on CI just to make sure that they compile and finish successfully
> Performance tests on CI

- Nuke.xcodeproj/project.pbxproj
- README.md
- Sources/ImagePipeline.swift
- Sources/ImagePipelineConfiguration.swift
- Tests/ImagePipelineProcessorTests.swift
This PR implements the feature discussed in #269
> ImagePipeline processors

- Demo/Resources/IB/Base.lproj/Main.storyboard
| before | after |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/1515107/66863360-b29f1f80-ef47-11e9-8db2-933d8402b4d3.png)  | ![image2](https://user-images.githubusercontent.com/1515107/66863369-b632a680-ef47-11e9-855d-cbf540671eaf.png)  |
> fix demo app label color in dark mode

- Nuke.podspec
This closes #330 
Ref: [CocoaPods's Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html#swift_versions)
> Add Swift version to podspec

- Sources/ImagePreheater.swift
- Tests/ImagePreheaterTests.swift
> ImagePreheater to Automatically Cancel Tasks on Deinit

- Demo/Cartfile
- Demo/Cartfile.resolved
- Demo/NukeDemo.xcodeproj/project.pbxproj
- Demo/NukeDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Demo/Sources/AnimatedImageViewController.swift
- Demo/Sources/MenuViewController.swift
- README.md
- Scripts/validate_demo.sh
> Remove FLAnimatedImage from demo

- Documentation/Guides/Performance Guide.md
- Documentation/Guides/Troubleshooting.md
- Documentation/Guides/image-formats.md
- Documentation/Guides/image-pipeline.md
- README.md
- Sources/ImageCache.swift
- Sources/ImagePipelineConfiguration.swift
- Sources/ImageProcessing.swift
- Sources/ImageRequest.swift
- Sources/ImageTask.swift
- Sources/ImageViewExtensions.swift
- Tests/ImagePipelineTests/ImagePipelineObservingTests.swift
Hi 👋 , this PR contains some small updates to the documentation (markdown and code comments).
There are no code changes. Most of the changes are just fixing typos and other small things.
There are a few changes to the [`ImagePipeline.loadImage(with:completion:)`](https://github.com/nonsensery/Nuke/blob/3bf642eb15c938e5f3587c86cb0c65d47bd4fb88/Documentation/Guides/image-pipeline.md#imagepipelineloadimagewithcompletion) section in "image-pipeline.md" that are a bit more editorial.
Let me know what you think. I'm happy to revise the changes if desired.
> Documentation updates and clarifications

- Sources/Internal.swift
- Tests/ImagePipelineTests/ImagePipelineResumableDataTests.swift
- Tests/ResumableDataTests.swift
Fixes https://github.com/kean/Nuke/issues/389
> #389 Fix an issue where fully downloaded data will sometimes be saved as resumable

- Nuke.xcodeproj/project.pbxproj
- Sources/ImagePublisher.swift
- Sources/ImageRequest.swift
You are no longer going to need to install [ImagePublisher](https://github.com/kean/ImagePublisher) package to use Combine extensions
> Add ImagePublisher

- Sources/ImageDecoding.swift
https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format
> Fix typo: Effeciency -> Efficiency

- Sources/UI/ImageViewExtensions.swift
Thank you for the nice update to version10!!
This is just a small fix of doc comment.
> Fix: doc comment

- Sources/Core/ImageProcessing.swift
> fix: restore watchOS builds

- Sources/Core/Decoding/ImageDecoders+Video.swift
- Sources/Core/ImageResponse.swift
- Sources/Internal/AVDataAsset.swift
I tried to play m4v through NukeUI, but found an issue where the conversion failed in ImageContainer. Post a PR that fixes the problem.
> Support m4v

- README.md
Per our convo on Twitter. Let me know if you'd like anything changed.
> Add Keygen sponsorship

- Sources/Core/Decoding/AssetType.swift
- Sources/Internal/AVDataAsset.swift
This is the initial version for adding .mov file support. Issue #533
> Add support for .mov files.

- Sources/NukeUI/Internal.swift
- Sources/NukeUI/LazyImage.swift
- Sources/NukeUI/VideoPlayerView.swift
Adds the rest of the `UIView.ContentMode` counterparts.
> Add missing content modes

- Sources/Nuke/Prefetching/ImagePrefetcher.swift
This commit fixes `didComplete` in `ImagePrefetcher` not being called in cases of failure or cancellation. Usually that happens when the image has been found in cache.
> Fixes #616: wrong `didComplete` behaviour.

- Sources/Nuke/Internal/Extensions.swift
- Sources/Nuke/Pipeline/ImagePipelineConfiguration.swift
- Sources/Nuke/Tasks/TaskFetchOriginalImageData.swift
- Sources/Nuke/Tasks/TaskLoadImage.swift
- Tests/NukeTests/ImagePipelineTests/ImagePipelineDataCacheTests.swift
- Tests/NukeTests/ImagePipelineTests/ImagePipelineImageCacheTests.swift
- Update `ImageRequest/DataCachePolicy` documentation
- Fix an issue where processed images for local resources were not stored (for policies that enable this cache)
> Clarify data cache policies

- Tests/NukeThreadSafetyTests/ThreadSafetyTests.swift
- Tests/XCTestCaseExtensions.swift
Hi,
This PR replaces legacy random API with new API to improve random number generation.
> Improve random number generation

- Sources/Nuke/Caching/DataCache.swift
Move `DataCache` metadata to a hidden file to address https://github.com/kean/Nuke/issues/717
> Move DataCache metadata to file

- README.md
Nuke does not render SVG out of the box, let's make sure we don't mislead people on this
> Updating misleading SVG support
